on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TERRAGRUNT_LOG_LEVEL: debug
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          cache: true
      - name: lint
        uses: golangci/golangci-lint-action@v3
        with:
          skip-cache: true
      - name: run tests
        run: make test
      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v3
